apiVersion: apps/v1
kind: Deployment
metadata:
  name: faq-app-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: faq-app
  template:
    metadata:
      labels:
        app: faq-app
    spec:
      containers:
        - name: faq-app
          image: yash5090/faq-app:latest # Replace with the actual image tag
          ports:
            - containerPort: 5000 # Replace with the port your Tetris game listens on
